### ISSUE TITLE
warning sui dati di test

### ISSUE THREAD

**Issue by iannellog** [FrancescaR11/ESERCIZIO_TAXI#2]
ho fatto pull e provato a eseguire il programma sui dati di test
ha girato, ma stampa questo warning:

sys:1: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.

Quando averte tempo provate a capire se si può eliminare

**Comment by FrancescaR11** [comment]
Abbiamo eliminato il warning specificando low_memory=False in get_list_of_taxi, nella classe CSVReader.
